name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DockerHub_Public
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/{secrets.DOCKERHUB_REPO}/demo:latest .

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/{secrets.DOCKERHUB_REPO}/demo:latest
