name: Demand Forecast Github Actions CICD Demo

on:
  push:
    branches: [main]

jobs:
  peng_is_the_best:
    runs-on: ubuntu-latest
    environment: DockerHub_Public
    steps:
      - uses: actions/checkout@v7

      - name: dockerhub login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: image build and push to dockerhub public
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPO}}:peng_demo .
          docker push ${{ secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPO}}:peng_demo